version: '3.8'

services:
  backend:
    build:
      context: TradingBot
    ports:
      - "5000:5000"
    # Uncomment to persist SQLite data
    #volumes:
    #  - ./Data:/app/Data

  frontend:
    build:
      context: Frontend/tradingbot
    ports:
      - "3000:80"
    depends_on:
      - backend
        
  predictor:
    build:
      context: PredictionModel
    ports:
      # TODO: Remove after integration with backend
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
