version: '3.8'

services:
  backend:
    build:
      context: TradingBot
    ports:
      - "5000:5000"
    depends_on:
      - predictor
    volumes:
      - ./TradingBot/Data:/app/Data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1s

  frontend:
    build:
      context: Frontend/tradingbot
    ports:
      - "3000:80"
    depends_on:
      - backend
        
  predictor:
    build:
      context: PredictionModel
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 20s
