### Predict
GET http://localhost:5000/manual-tests/predict
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Accept: application/json

### Market data
GET http://localhost:5000/manual-tests/market-data
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Accept: application/json

### Single symbol
GET http://localhost:5000/manual-tests/market-data/AMZN
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Accept: application/json

### Trading actions execution
POST http://localhost:5000/manual-tests/trading-actions
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Content-Type: application/json

{
  "symbol": "TQQQ",
  "quantity": 1,
  "price": 50,
  "orderType": "LimitBuy",
  "inForce": "Day"
}

### Strategy results execution
GET http://localhost:5000/manual-tests/strategy-results
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Content-Type: application/json
